# Generated by Django 3.0.8 on 2021-02-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_doctor_patient_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='profile_pic',
            field=models.FileField(blank=True, default='default.png', upload_to='doctor_finder/images/'),
        ),
        migrations.AddField(
            model_name='patient',
            name='profile_pic',
            field=models.FileField(blank=True, default='default.png', upload_to='doctor_finder/images/'),
        ),
    ]
