# Generated by Django 3.0.8 on 2021-02-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_doctor_patient_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='profile_pic',
            field=models.FileField(blank=True, default='default.png', upload_to='doctor_finder/images/'),
        ),
    ]
