# Generated by Django 3.0.8 on 2021-03-03 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_case'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField()),
                ('appointment_status', models.BooleanField(default=False)),
                ('case_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Case')),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Doctor')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Patient')),
            ],
        ),
    ]
