# Generated by Django 3.0.8 on 2021-03-03 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='case_id',
        ),
        migrations.DeleteModel(
            name='Case',
        ),
    ]
