# Generated by Django 3.0.8 on 2021-03-03 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20210303_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
