# Generated by Django 3.0.8 on 2021-03-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_appointment_case_doctor_patient_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_status',
            field=models.CharField(default='active', max_length=10),
        ),
    ]
